<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default_book_4_Manual_DataSource.aspx.cs" Inherits="Ch10_Default_book_4_Manual_DataSource" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>除了GridView之外, 其他程式 100%都是手寫的</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <strong><span style="color: #ff0000">除了GridView之外, 其他程式 100%都是手寫的<br />
            <span style="color: #3300ff; text-decoration: underline">HTML畫面上，沒有 SqlDatasource</span></span></strong><br />
        <span style="font-size: 11pt"></span>
        <ul>
            <li><span style="font-size: 10pt"><span>GridView的 [EnableSortingAndPagingCallsPack]屬性要<span
                style="color: #ff0000">關閉(False)</span>, 否則自己寫的 [分頁]程式不會運作</span> </span></li>
            <li><span style="font-size: 10pt"><span>GridView的 <span style="color: #ff0000">DataSource<strong><span>ID</span></strong></span>無法使用,
                因為SqlDataSource控制項 自己寫在後置程式碼， 沒有在 <span style="color: #3300ff">HTML</span>畫面中</span> </span>
            </li>
            <li><span></span><span style="font-size: 10pt">畫面的GridView必須設定「DataKeyNames = "<span
                style="font-size: 12pt; background-color: #ffff33"><strong>id</strong></span>"」屬性（事先設定好資料庫的「<strong>主索引鍵</strong>」）</span></li>
        </ul>
        <span style="font-size: 11pt">
            <hr />
            <span style="color: #ff0000">SqlDataSource SqlDataSource1 = new SqlDataSource();
        <br />
            </span>
            <br />
            //<span style="color: #ff0033">==自己手動撰寫 SqlDataSource ,必須先寫<span style="background-color: #ffcc66">下面三行</span>
                ==
                <br />
            </span>//<span style="font-size: 10pt"><span style="color: #006633">== 連結資料庫的連接字串 </span>
                <br />
                SqlDataSource1.<span style="background-color: #ffcc66">ConnectionString</span> =
                System.Web.Configuration.WebConfigurationManager.ConnectionStrings["testConnectionString"].ConnectionString 
        ;<br />
                //<span style="color: #006633">== 撰寫SQL指令 ==
                <br />
                </span>SqlDataSource1.<span style="background-color: #ffcc66">SelectCommand</span> =
                "SELECT * FROM [test]";
                <br />
                SqlDataSource1.<span style="background-color: #ffcc66">DataSourceMode </span>= SqlDataSourceMode.<span
                    style="background-color: #ffff33">DataSet;</span></span></span><br />
        <br />
        <asp:GridView ID="GridView1" runat="server" CellPadding="4" ForeColor="#333333"
            AllowPaging="True" Font-Size="Small" PageSize="5" ShowFooter="True"
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id"
            OnPageIndexChanged="GridView1_PageIndexChanged"
            OnPageIndexChanging="GridView1_PageIndexChanging"
            OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting"
            OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating">
            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <RowStyle BackColor="#E3EAEB" />
            <EditRowStyle BackColor="#7C6F57" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <AlternatingRowStyle BackColor="White" />
        </asp:GridView>

    </div>
    </form>

</body>
</html>
